name: quantum_production
channels:
  - defaults
dependencies:
  - python=3.6
  - fiona
  - matplotlib
  - numpy
  - nb_conda_kernels
  - pandas
  - pyproj
  - rasterio
  - scikit-learn
  - scipy
  - shapely
